CREATE TABLE IF NOT EXISTS users
(
    id    INT4 GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL UNIQUE,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS requests
(
    id          INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(512),
    requestor   INT4 REFERENCES users (id) ON DELETE CASCADE,
    created     TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE IF NOT EXISTS items
(
    id           INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255),
    description  VARCHAR(512),
    is_available BOOLEAN,
    owner_id     INT4 REFERENCES users (id) ON DELETE CASCADE,
    request_id   INT4 REFERENCES requests (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    item_id    INT4 REFERENCES items (id) ON DELETE CASCADE,
    booker_id  INT4 REFERENCES users (id) ON DELETE CASCADE,
    status     VARCHAR(40)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        INT4 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      VARCHAR(512),
    item_id   INT4 REFERENCES items (id) ON DELETE CASCADE,
    author_id INT4 REFERENCES users (id) ON DELETE CASCADE,
    created   TIMESTAMP WITHOUT TIME ZONE
);


